name: 📚 Build Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Create ZIP
        run: |
          mkdir export
          cp -r build/antworten ./export/
          cp -r input ./export/
          cd export
          zip -r ../wahlcheck-antworten.zip .

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: wahlcheck-antworten.zip